#cloud-config
users:
  - name: web
    primary_group: web
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIxWFP6hNA55TryFLdaTVEE11w1nYP3HFcN/zGc4WS3E anges@root

package_update: true
package_upgrade: true
packages:
  - nginx
  - nmap
